
package org.tempuri;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICryptoCurrency", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface ICryptoCurrency {


    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetSupportedCurrencies", action = "http://tempuri.org/ICryptoCurrency/GetSupportedCurrencies")
    @WebResult(name = "GetSupportedCurrenciesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSupportedCurrencies", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedCurrencies")
    @ResponseWrapper(localName = "GetSupportedCurrenciesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedCurrenciesResponse")
    public ArrayOfstring getSupportedCurrencies();

    /**
     * 
     * @param currencyCode
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsCurrencySupported", action = "http://tempuri.org/ICryptoCurrency/IsCurrencySupported")
    @WebResult(name = "IsCurrencySupportedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsCurrencySupported", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsCurrencySupported")
    @ResponseWrapper(localName = "IsCurrencySupportedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsCurrencySupportedResponse")
    public Boolean isCurrencySupported(
        @WebParam(name = "currencyCode", targetNamespace = "http://tempuri.org/")
        String currencyCode);

    /**
     * 
     * @param currencyCodeFrom
     * @param currencyCodeTo
     * @param value
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "Convert", action = "http://tempuri.org/ICryptoCurrency/Convert")
    @WebResult(name = "ConvertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertResponse")
    public BigDecimal convert(
        @WebParam(name = "currencyCodeFrom", targetNamespace = "http://tempuri.org/")
        String currencyCodeFrom,
        @WebParam(name = "currencyCodeTo", targetNamespace = "http://tempuri.org/")
        String currencyCodeTo,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        BigDecimal value);

}
