
package org.doge.lab2.client.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICalculator", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
        ObjectFactory.class
})
public interface ICalculator {


    /**
     * 
     */
    @WebMethod(operationName = "Ping", action = "http://tempuri.org/ICalculator/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PingResponse")
    public void ping();

    /**
     * 
     * @param number
     * @param number2
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Add", action = "http://tempuri.org/ICalculator/Add")
    @WebResult(name = "AddResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Add", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Add")
    @ResponseWrapper(localName = "AddResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.AddResponse")
    public Double add(
        @WebParam(name = "number", targetNamespace = "http://tempuri.org/")
        Double number,
        @WebParam(name = "number2", targetNamespace = "http://tempuri.org/")
        Double number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Substract", action = "http://tempuri.org/ICalculator/Substract")
    @WebResult(name = "SubstractResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Substract", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Substract")
    @ResponseWrapper(localName = "SubstractResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SubstractResponse")
    public Double substract(
        @WebParam(name = "number1", targetNamespace = "http://tempuri.org/")
        Double number1,
        @WebParam(name = "number2", targetNamespace = "http://tempuri.org/")
        Double number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Multiply", action = "http://tempuri.org/ICalculator/Multiply")
    @WebResult(name = "MultiplyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Multiply", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Multiply")
    @ResponseWrapper(localName = "MultiplyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MultiplyResponse")
    public Double multiply(
        @WebParam(name = "number1", targetNamespace = "http://tempuri.org/")
        Double number1,
        @WebParam(name = "number2", targetNamespace = "http://tempuri.org/")
        Double number2);

    /**
     * 
     * @param number1
     * @param number2
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Divide", action = "http://tempuri.org/ICalculator/Divide")
    @WebResult(name = "DivideResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Divide", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Divide")
    @ResponseWrapper(localName = "DivideResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DivideResponse")
    public Double divide(
        @WebParam(name = "number1", targetNamespace = "http://tempuri.org/")
        Double number1,
        @WebParam(name = "number2", targetNamespace = "http://tempuri.org/")
        Double number2);

    /**
     * 
     * @param number1
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Power", action = "http://tempuri.org/ICalculator/Power")
    @WebResult(name = "PowerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Power", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Power")
    @ResponseWrapper(localName = "PowerResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PowerResponse")
    public Double power(
        @WebParam(name = "number1", targetNamespace = "http://tempuri.org/")
        Double number1);

}
