
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfUnitTypeArrayOfstrings3DCQ8F0;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.cloudcomputing_lab2_unitsconverter.ArrayOfUnitType;
import org.datacontract.schemas._2004._07.cloudcomputing_lab2_unitsconverter.UnitType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUnitsConverter", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.cloudcomputing_lab2_unitsconverter.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IUnitsConverter {


    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.cloudcomputing_lab2_unitsconverter.ArrayOfUnitType
     */
    @WebMethod(operationName = "GetSupportedTypes", action = "http://tempuri.org/IUnitsConverter/GetSupportedTypes")
    @WebResult(name = "GetSupportedTypesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSupportedTypes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedTypes")
    @ResponseWrapper(localName = "GetSupportedTypesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedTypesResponse")
    public ArrayOfUnitType getSupportedTypes();

    /**
     * 
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfUnitTypeArrayOfstrings3DCQ8F0
     */
    @WebMethod(operationName = "GetSupportedUnits", action = "http://tempuri.org/IUnitsConverter/GetSupportedUnits")
    @WebResult(name = "GetSupportedUnitsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSupportedUnits", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedUnits")
    @ResponseWrapper(localName = "GetSupportedUnitsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedUnitsResponse")
    public ArrayOfKeyValueOfUnitTypeArrayOfstrings3DCQ8F0 getSupportedUnits();

    /**
     * 
     * @param type
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring
     */
    @WebMethod(operationName = "GetSupportedUnitsByType", action = "http://tempuri.org/IUnitsConverter/GetSupportedUnitsByType")
    @WebResult(name = "GetSupportedUnitsByTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSupportedUnitsByType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedUnitsByType")
    @ResponseWrapper(localName = "GetSupportedUnitsByTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSupportedUnitsByTypeResponse")
    public ArrayOfstring getSupportedUnitsByType(
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        UnitType type);

    /**
     * 
     * @param code
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsUnitCodeSupported", action = "http://tempuri.org/IUnitsConverter/IsUnitCodeSupported")
    @WebResult(name = "IsUnitCodeSupportedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsUnitCodeSupported", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsUnitCodeSupported")
    @ResponseWrapper(localName = "IsUnitCodeSupportedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsUnitCodeSupportedResponse")
    public Boolean isUnitCodeSupported(
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code);

    /**
     * 
     * @param type
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsUnitTypeSupported", action = "http://tempuri.org/IUnitsConverter/IsUnitTypeSupported")
    @WebResult(name = "IsUnitTypeSupportedResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "IsUnitTypeSupported", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsUnitTypeSupported")
    @ResponseWrapper(localName = "IsUnitTypeSupportedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.IsUnitTypeSupportedResponse")
    public Boolean isUnitTypeSupported(
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        UnitType type);

    /**
     * 
     * @param from
     * @param to
     * @param value
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Convert", action = "http://tempuri.org/IUnitsConverter/Convert")
    @WebResult(name = "ConvertResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ConvertResponse")
    public Double convert(
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        String from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        String to,
        @WebParam(name = "value", targetNamespace = "http://tempuri.org/")
        Double value);

}
